# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build: .
    container_name: app-beyourboss-mobile
    volumes:
      - ./:/app
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
